/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20Sol from "./ERC20.sol";
export type { erc20Sol };
export type { Greeter } from "./Greeter";
export type { Marketplace } from "./Marketplace";
export type { NFT721 } from "./NFT721";
